### ISSUE TITLE
is it possible to change google's re2 repository address?

### ISSUE THREAD

**Issue by xrzhao** [tuncer/re2#14]
in c_src/build_deps.sh:

change:
    git clone https://code.googlesource.com/re2
to: 
    git clone https://github.com/google/re2.git

**Comment by tuncer** [comment]
If you have a new enough (lib)re2 installed on your system, you can set the `SYSTEM_RE2` env var to avoid fetching and building a local copy.

Also, have you tried using git's url.insteadOf feature? If that works, please post the details, so that we can include it in the docs. If that does not work, we can introduce a repo override (`RE2_REPO` env var).

googlesource has higher availability and more consistent response times, so I'd prefer to keep the default as is.

Thoughts?

**Comment by tuncer** [comment]
ping?

**Comment by tuncer** [comment]
ping?

**Comment by tuncer** [comment]
@xrzhao, given no feedback regarding the suggested solutions, I'm going to assume one of them worked for you. Please reopen if that's not the case.
